baseURL = 'https://sashco-m.github.io'
languageCode = 'en-us'
title = 'sashco'
theme = "hugo-theme-console"
enableEmoji = true
pygmentsCodefences = true 
pygmentsStyle = "dracula"

[params]
  # Cutting off the page title to two chars for mobile (console-demo -> co)
  titleCutting = true

  # Set the animation style -- https://animate.style/
  # To disable animations, please remove or comment animationStyle parameter
  animateStyle = "animated zoomIn fast" 
  
  [[params.navlinks]]
  name = "resume/"
  url = "https://sashcoresumebucket.s3.us-east-2.amazonaws.com/mistelbacher_resume.pdf"

  [[params.navlinks]]
  name = "posts/"
  url = "posts/"
  
  [[params.navlinks]]
  name = "photos/"
  url = "photos/"

[deployment]
order = [".jpg$", ".gif$"]


[[deployment.targets]]
name = "sashco-hugo"
# S3; see https://gocloud.dev/howto/blob/#s3
# For S3-compatible endpoints, see https://gocloud.dev/howto/blob/#s3-compatible
URL = "s3://sashco-hugo-bucket?region=us-east-1"

[outputFormats]
  [outputFormats.SearchIndex]
    baseName = "search"
    mediaType = "application/json"

[outputs]
  home = ["HTML","SearchIndex"]
  page = ["HTML"]